version: "3"
services:
  rails_server:
    build: rails_server
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    volumes:
      - ./:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis
  socket_io:
    build: socket_io
    command: npm start

  redis:
    image: redis:3.2
    ports:
      - 6379:6379
  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  bundle:
  pg_data:

