version: "3"
services:
  nginx:
    image: nginx
    links:
      - rails_server
      - socket_io
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    ports:
      - 80:80

  rails_server:
    build: rails_server
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    environment:
      - PORT=5000
    env_file:
      - rails_server/.env
    volumes:
      - ./rails_server:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis


  example_service:
    build: example_service
    command: python3 main.py
    volumes:
      - ./example_service:/code
    links:
      - redis

  sidekiq:
    build: rails_server
    command: sidekiq -C config/sidekiq.yml
    env_file:
      - rails_server/.env
    volumes:
      - ./rails_server:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis

  socket_io:
    build: socket_io
    command: npm start
    links:
      - redis
    ports:
      - 4200:4200
    volumes:
      - ./socket_io:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  redis:
    image: redis:3.2

  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  bundle:
  pg_data:
  node_modules:
