version: "3"
services:
  nginx:
    image: nginx
    links:
      - rails_server
      - socket_io
    volumes:
      - ./slackerboard/dist:/var/slackerboard
      - ./nginx/prod/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/prod/ssl.conf:/etc/nginx/ssl.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /tmp/letsencrypt/www:/tmp/letsencrypt/www
    ports:
      - 80:80
      - 443:443
      - 4200:4200

  rails_server:
    build: services/rails_server
    command: bundle exec rails s -p 5000 -b 0.0.0.0
    environment:
      - PORT=5000
      - RAILS_ENV=production
    env_file:
      - ./rails_server/.env
    volumes:
      - ./rails_server:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis

  sidekiq:
    build: services/rails_server
    command: sidekiq -C config/sidekiq.yml
    env_file:
      - ./rails_server/.env
    volumes:
      - ./rails_server:/home/app/webapp
      - bundle:/usr/local/bundle
    links:
      - postgres
      - redis

  socket_io:
    build: services/socket_io
    command: npm start
    links:
      - redis
    volumes:
      - ./socket_io:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  redis:
    image: redis:3.2

  postgres:
    image: postgres:9.6
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  bundle:
  pg_data:
  node_modules:
